// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/StatPy/Lexer.jflex

// ------------  Paquete e importaciones ------------
package StatPy; 

import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\6"+
    "\1\7\1\10\1\0\1\11\1\0\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\12\24"+
    "\1\25\1\26\1\27\1\30\1\31\2\0\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\52"+
    "\1\63\1\64\1\65\1\0\1\66\1\0\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\52"+
    "\1\67\1\70\1\71\7\0\1\3\252\0\2\72\115\0"+
    "\1\73\u01a8\0\2\3\u0100\0\1\74\325\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\2\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\16\24\1\25"+
    "\1\26\1\27\1\1\1\30\2\1\1\31\1\0\1\32"+
    "\1\0\1\33\1\0\1\34\1\0\1\35\1\36\3\0"+
    "\1\37\1\40\1\41\6\24\1\42\5\24\1\43\7\24"+
    "\1\0\4\24\1\44\1\43\3\0\1\32\1\34\1\0"+
    "\2\45\1\46\3\24\1\0\6\24\1\0\1\24\1\47"+
    "\1\24\1\50\1\24\1\0\3\24\1\0\2\24\1\0"+
    "\2\24\1\0\1\24\1\0\1\24\1\0\1\50\3\0"+
    "\1\51\1\24\2\52\1\53\1\24\1\0\2\24\1\0"+
    "\1\24\1\54\2\55\1\24\1\0\1\24\2\56\2\24"+
    "\1\0\1\24\1\0\1\24\1\57\1\0\1\24\2\60"+
    "\1\24\1\0\1\24\2\0\1\45\2\61\1\24\1\0"+
    "\2\24\1\0\1\24\2\62\1\24\1\0\2\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\2\63\2\64\1\24"+
    "\1\0\2\24\1\0\1\65\1\24\1\0\1\24\2\66"+
    "\2\67\2\70\1\24\2\71\1\72\1\24\1\0\1\24"+
    "\1\0\1\24\1\73\1\74\1\73\1\74\2\75\1\24"+
    "\1\0\2\24\2\0\1\76\1\24\1\0\2\24\2\0"+
    "\1\24\1\0\1\24\2\77\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\2\100"+
    "\1\24\1\0\2\101";

  private static int [] zzUnpackAction() {
    int [] result = new int[256];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\75\0\75\0\172\0\267\0\75\0\364"+
    "\0\u0131\0\75\0\75\0\75\0\u016e\0\75\0\u01ab\0\75"+
    "\0\u01e8\0\u0225\0\75\0\75\0\u0262\0\u029f\0\u02dc\0\u0319"+
    "\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487\0\u04c4\0\u0501"+
    "\0\u053e\0\u057b\0\u05b8\0\u05f5\0\u0632\0\75\0\75\0\75"+
    "\0\u066f\0\75\0\u06ac\0\u06e9\0\75\0\267\0\75\0\u0726"+
    "\0\75\0\u0763\0\75\0\u07a0\0\75\0\75\0\u07dd\0\u081a"+
    "\0\u0857\0\75\0\75\0\75\0\u0894\0\u08d1\0\u090e\0\u094b"+
    "\0\u0988\0\u09c5\0\u0a02\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6\0\u0b33"+
    "\0\u0319\0\u0b70\0\u0bad\0\u0bea\0\u0c27\0\u0c64\0\u0ca1\0\u0cde"+
    "\0\u0d1b\0\u0d58\0\u0d95\0\u0dd2\0\u0e0f\0\75\0\75\0\u0e4c"+
    "\0\u0e89\0\u0ec6\0\267\0\u0763\0\u0f03\0\75\0\u0f40\0\u0857"+
    "\0\u0f7d\0\u0fba\0\u0ff7\0\u1034\0\u1071\0\u10ae\0\u10eb\0\u1128"+
    "\0\u1165\0\u11a2\0\u11df\0\u121c\0\u0319\0\u1259\0\u0319\0\u1296"+
    "\0\u12d3\0\u1310\0\u134d\0\u138a\0\u13c7\0\u1404\0\u1441\0\u147e"+
    "\0\u14bb\0\u14f8\0\u1535\0\u1572\0\u15af\0\u15ec\0\u1629\0\75"+
    "\0\u1666\0\u16a3\0\u16e0\0\u0319\0\u171d\0\u0319\0\75\0\u0319"+
    "\0\u175a\0\u1797\0\u17d4\0\u1811\0\u184e\0\u188b\0\u0319\0\u0319"+
    "\0\75\0\u18c8\0\u1905\0\u1942\0\u0319\0\75\0\u197f\0\u19bc"+
    "\0\u19f9\0\u1a36\0\u1a73\0\u1ab0\0\u0319\0\u1aed\0\u1b2a\0\u0319"+
    "\0\75\0\u1b67\0\u1ba4\0\u1be1\0\u1c1e\0\u1c5b\0\u1c5b\0\u0319"+
    "\0\75\0\u1c98\0\u1cd5\0\u1d12\0\u1d4f\0\u1d8c\0\u1dc9\0\u0319"+
    "\0\75\0\u1e06\0\u1e43\0\u1e80\0\u1ebd\0\u1efa\0\u1f37\0\u1f74"+
    "\0\u1fb1\0\u1fee\0\u202b\0\u0319\0\75\0\u0319\0\75\0\u2068"+
    "\0\u20a5\0\u20e2\0\u211f\0\u215c\0\u0319\0\u2199\0\u21d6\0\u2213"+
    "\0\u0319\0\75\0\u0319\0\75\0\u2250\0\u228d\0\u22ca\0\u0319"+
    "\0\75\0\u0319\0\u2307\0\u2344\0\u2381\0\u23be\0\u23fb\0\u0319"+
    "\0\u0319\0\75\0\75\0\u0319\0\75\0\u2438\0\u2475\0\u24b2"+
    "\0\u24ef\0\u252c\0\u2569\0\u0319\0\u25a6\0\u25e3\0\u2620\0\u265d"+
    "\0\u269a\0\u26d7\0\u2714\0\u2751\0\u278e\0\u0319\0\75\0\u27cb"+
    "\0\u2808\0\u2845\0\u2882\0\u28bf\0\u28fc\0\u2939\0\u2976\0\u29b3"+
    "\0\u29f0\0\u2a2d\0\u0319\0\75\0\u2a6a\0\u2aa7\0\u0319\0\75";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[256];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\3\3\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\30"+
    "\1\37\3\30\1\40\1\41\4\30\1\42\1\43\1\30"+
    "\1\44\1\45\2\30\1\46\1\2\1\47\1\2\1\50"+
    "\1\51\1\52\1\53\1\54\1\2\125\0\1\55\44\0"+
    "\2\56\1\0\5\56\1\57\53\56\1\60\10\56\12\0"+
    "\1\61\62\0\1\62\2\0\5\62\1\0\2\62\1\63"+
    "\50\62\1\64\10\62\17\0\1\65\76\0\1\66\71\0"+
    "\1\67\4\0\1\70\73\0\1\71\1\0\1\22\100\0"+
    "\1\72\74\0\1\73\74\0\1\74\70\0\1\30\5\0"+
    "\31\30\3\0\1\30\32\0\1\30\5\0\16\30\1\75"+
    "\2\30\1\76\7\30\3\0\1\30\32\0\1\30\5\0"+
    "\1\77\6\30\1\100\6\30\1\101\12\30\3\0\1\30"+
    "\32\0\1\30\5\0\4\30\1\102\11\30\1\103\12\30"+
    "\3\0\1\30\32\0\1\30\5\0\11\30\1\104\1\30"+
    "\1\105\15\30\3\0\1\30\32\0\1\30\5\0\1\106"+
    "\15\30\1\107\12\30\3\0\1\30\32\0\1\30\5\0"+
    "\21\30\1\110\7\30\3\0\1\30\32\0\1\30\5\0"+
    "\5\30\1\111\7\30\1\112\13\30\3\0\1\30\32\0"+
    "\1\30\5\0\1\113\30\30\3\0\1\30\32\0\1\30"+
    "\5\0\4\30\1\114\24\30\3\0\1\30\32\0\1\30"+
    "\5\0\23\30\1\115\2\30\1\116\2\30\3\0\1\30"+
    "\32\0\1\30\5\0\10\30\1\117\10\30\1\120\7\30"+
    "\3\0\1\30\3\0\1\121\26\0\1\30\5\0\1\122"+
    "\15\30\1\123\12\30\3\0\1\30\32\0\1\30\5\0"+
    "\7\30\1\124\11\30\1\125\7\30\3\0\1\30\76\0"+
    "\1\126\43\0\1\127\7\0\1\130\102\0\1\131\2\0"+
    "\1\132\14\0\2\56\1\0\5\56\1\133\53\56\1\60"+
    "\10\56\13\0\1\63\71\0\1\62\2\0\1\134\33\0"+
    "\1\62\5\0\1\62\17\0\16\67\1\135\56\67\2\70"+
    "\1\136\2\0\1\137\67\70\6\0\1\140\15\0\1\140"+
    "\43\0\1\140\30\0\1\30\5\0\16\30\1\141\12\30"+
    "\3\0\1\30\32\0\1\30\5\0\4\30\1\142\24\30"+
    "\3\0\1\30\32\0\1\30\5\0\22\30\1\143\6\30"+
    "\3\0\1\30\4\0\1\144\25\0\1\30\5\0\1\145"+
    "\30\30\3\0\1\30\32\0\1\30\5\0\15\30\1\146"+
    "\13\30\3\0\1\30\32\0\1\30\5\0\5\30\1\147"+
    "\23\30\3\0\1\30\32\0\1\30\5\0\24\30\1\150"+
    "\4\30\3\0\1\30\32\0\1\30\5\0\4\30\1\151"+
    "\24\30\3\0\1\30\32\0\1\30\5\0\22\30\1\152"+
    "\6\30\3\0\1\30\4\0\1\153\25\0\1\30\5\0"+
    "\13\30\1\154\15\30\3\0\1\30\32\0\1\30\5\0"+
    "\21\30\1\155\7\30\3\0\1\30\32\0\1\30\5\0"+
    "\1\156\30\30\3\0\1\30\32\0\1\30\5\0\23\30"+
    "\1\157\5\30\3\0\1\30\32\0\1\30\5\0\10\30"+
    "\1\160\20\30\3\0\1\30\3\0\1\161\26\0\1\30"+
    "\5\0\26\30\1\162\2\30\3\0\1\30\32\0\1\30"+
    "\5\0\21\30\1\163\7\30\3\0\1\30\32\0\1\30"+
    "\5\0\10\30\1\164\20\30\3\0\1\30\3\0\1\165"+
    "\26\0\1\30\5\0\23\30\1\166\5\30\3\0\1\30"+
    "\32\0\1\30\5\0\24\30\1\167\4\30\3\0\1\30"+
    "\63\0\1\170\43\0\1\30\5\0\13\30\1\171\15\30"+
    "\3\0\1\30\32\0\1\30\5\0\10\30\1\172\20\30"+
    "\3\0\1\30\3\0\1\173\26\0\1\30\5\0\10\30"+
    "\1\174\20\30\3\0\1\30\3\0\1\175\26\0\1\30"+
    "\5\0\10\30\1\176\20\30\3\0\1\30\3\0\1\177"+
    "\57\0\1\200\72\0\1\201\63\0\1\165\27\0\1\165"+
    "\2\0\16\202\1\203\4\202\1\136\51\202\2\0\1\136"+
    "\116\0\1\30\5\0\13\30\1\204\15\30\3\0\1\30"+
    "\32\0\1\30\5\0\1\205\30\30\3\0\1\30\32\0"+
    "\1\30\5\0\4\30\1\206\24\30\3\0\1\30\44\0"+
    "\1\207\62\0\1\30\5\0\21\30\1\210\7\30\3\0"+
    "\1\30\32\0\1\30\5\0\22\30\1\211\6\30\3\0"+
    "\1\30\4\0\1\212\25\0\1\30\5\0\1\213\7\30"+
    "\1\214\20\30\3\0\1\30\3\0\1\215\26\0\1\30"+
    "\5\0\1\30\1\216\27\30\3\0\1\30\32\0\1\30"+
    "\5\0\27\30\1\217\1\30\3\0\1\30\32\0\1\30"+
    "\5\0\4\30\1\220\24\30\3\0\1\30\44\0\1\221"+
    "\62\0\1\30\5\0\22\30\1\222\6\30\3\0\1\30"+
    "\4\0\1\223\25\0\1\30\5\0\5\30\1\224\23\30"+
    "\3\0\1\30\32\0\1\30\5\0\15\30\1\225\13\30"+
    "\3\0\1\30\55\0\1\226\51\0\1\30\5\0\25\30"+
    "\1\227\3\30\3\0\1\30\32\0\1\30\5\0\10\30"+
    "\1\230\20\30\3\0\1\30\3\0\1\231\26\0\1\30"+
    "\5\0\23\30\1\232\5\30\3\0\1\30\63\0\1\233"+
    "\43\0\1\30\5\0\24\30\1\234\4\30\3\0\1\30"+
    "\32\0\1\30\5\0\4\30\1\235\24\30\3\0\1\30"+
    "\64\0\1\236\42\0\1\30\5\0\16\30\1\237\12\30"+
    "\3\0\1\30\32\0\1\30\5\0\3\30\1\240\25\30"+
    "\3\0\1\30\43\0\1\241\63\0\1\30\5\0\13\30"+
    "\1\242\15\30\3\0\1\30\53\0\1\243\53\0\1\30"+
    "\5\0\23\30\1\244\5\30\3\0\1\30\63\0\1\245"+
    "\61\0\1\231\27\0\1\231\2\0\16\67\1\135\4\67"+
    "\1\246\67\67\1\135\4\67\1\247\51\67\24\0\1\30"+
    "\5\0\12\30\1\250\16\30\3\0\1\30\5\0\1\251"+
    "\24\0\1\30\5\0\16\30\1\252\12\30\3\0\1\30"+
    "\56\0\1\253\50\0\1\30\5\0\24\30\1\254\4\30"+
    "\3\0\1\30\32\0\1\30\5\0\15\30\1\255\13\30"+
    "\3\0\1\30\55\0\1\256\51\0\1\30\5\0\13\30"+
    "\1\257\15\30\3\0\1\30\32\0\1\30\5\0\4\30"+
    "\1\260\24\30\3\0\1\30\44\0\1\261\62\0\1\30"+
    "\5\0\10\30\1\262\20\30\3\0\1\30\3\0\1\263"+
    "\26\0\1\30\5\0\1\264\30\30\3\0\1\30\32\0"+
    "\1\30\5\0\15\30\1\265\13\30\3\0\1\30\55\0"+
    "\1\266\51\0\1\30\5\0\2\30\1\267\26\30\3\0"+
    "\1\30\42\0\1\270\64\0\1\30\5\0\13\30\1\271"+
    "\15\30\3\0\1\30\53\0\1\272\53\0\1\30\5\0"+
    "\21\30\1\273\7\30\3\0\1\30\32\0\1\30\5\0"+
    "\4\30\1\274\24\30\3\0\1\30\44\0\1\275\62\0"+
    "\1\30\5\0\4\30\1\276\24\30\3\0\1\30\44\0"+
    "\1\277\61\0\1\202\75\0\1\30\5\0\13\30\1\300"+
    "\15\30\3\0\1\30\53\0\1\301\53\0\1\30\5\0"+
    "\13\30\1\302\15\30\3\0\1\30\32\0\1\30\5\0"+
    "\10\30\1\303\20\30\3\0\1\30\3\0\1\304\44\0"+
    "\1\304\27\0\1\304\26\0\1\30\5\0\4\30\1\305"+
    "\24\30\3\0\1\30\32\0\1\30\5\0\2\30\1\306"+
    "\26\30\3\0\1\30\42\0\1\307\64\0\1\30\5\0"+
    "\13\30\1\310\15\30\3\0\1\30\32\0\1\30\5\0"+
    "\6\30\1\311\22\30\3\0\1\30\46\0\1\312\60\0"+
    "\1\30\5\0\7\30\1\313\21\30\3\0\1\30\47\0"+
    "\1\314\57\0\1\30\5\0\16\30\1\315\12\30\3\0"+
    "\1\30\56\0\1\316\50\0\1\30\5\0\4\30\1\317"+
    "\24\30\3\0\1\30\32\0\1\30\5\0\4\30\1\320"+
    "\24\30\3\0\1\30\44\0\1\321\62\0\1\30\5\0"+
    "\23\30\1\322\5\30\3\0\1\30\32\0\1\30\5\0"+
    "\21\30\1\323\7\30\3\0\1\30\61\0\1\324\45\0"+
    "\1\30\5\0\1\325\30\30\3\0\1\30\40\0\1\326"+
    "\66\0\1\30\5\0\16\30\1\327\12\30\3\0\1\30"+
    "\32\0\1\30\5\0\27\30\1\330\1\331\3\0\1\30"+
    "\67\0\1\332\1\333\36\0\1\30\5\0\22\30\1\334"+
    "\6\30\3\0\1\30\4\0\1\335\25\0\1\30\5\0"+
    "\6\30\1\336\22\30\3\0\1\30\46\0\1\337\60\0"+
    "\1\30\5\0\1\30\1\340\15\30\1\341\11\30\3\0"+
    "\1\30\41\0\1\342\15\0\1\343\47\0\1\30\5\0"+
    "\21\30\1\344\7\30\3\0\1\30\32\0\1\30\5\0"+
    "\13\30\1\345\15\30\3\0\1\30\53\0\1\346\53\0"+
    "\1\30\5\0\1\347\30\30\3\0\1\30\32\0\1\30"+
    "\5\0\10\30\1\350\20\30\3\0\1\30\3\0\1\351"+
    "\34\0\1\352\104\0\1\351\27\0\1\351\26\0\1\30"+
    "\5\0\16\30\1\353\12\30\3\0\1\30\56\0\1\354"+
    "\50\0\1\30\5\0\21\30\1\355\7\30\3\0\1\30"+
    "\32\0\1\30\5\0\4\30\1\356\24\30\3\0\1\30"+
    "\44\0\1\357\111\0\1\360\45\0\1\30\5\0\1\30"+
    "\1\361\27\30\3\0\1\30\41\0\1\362\65\0\1\30"+
    "\5\0\21\30\1\363\7\30\3\0\1\30\61\0\1\364"+
    "\45\0\1\30\5\0\1\365\30\30\3\0\1\30\40\0"+
    "\1\366\66\0\1\30\5\0\1\367\30\30\3\0\1\30"+
    "\40\0\1\370\66\0\1\30\5\0\13\30\1\371\15\30"+
    "\3\0\1\30\53\0\1\372\53\0\1\30\5\0\22\30"+
    "\1\373\6\30\3\0\1\30\4\0\1\374\55\0\1\374"+
    "\16\0\1\374\25\0\1\30\5\0\4\30\1\375\24\30"+
    "\3\0\1\30\44\0\1\376\62\0\1\30\5\0\22\30"+
    "\1\377\6\30\3\0\1\30\4\0\1\u0100\55\0\1\u0100"+
    "\16\0\1\u0100\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[10980];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\2\1\1\11\2\1\3\11\1\1\1\11"+
    "\1\1\1\11\2\1\2\11\21\1\3\11\1\1\1\11"+
    "\2\1\1\11\1\0\1\11\1\0\1\11\1\0\1\11"+
    "\1\0\2\11\3\0\3\11\24\1\1\0\4\1\2\11"+
    "\3\0\2\1\1\0\1\11\5\1\1\0\6\1\1\0"+
    "\5\1\1\0\3\1\1\0\2\1\1\0\2\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\11\3\0\3\1\1\11"+
    "\2\1\1\0\2\1\1\0\3\1\1\11\1\1\1\0"+
    "\2\1\1\11\2\1\1\0\1\1\1\0\2\1\1\0"+
    "\2\1\1\11\1\1\1\0\1\1\2\0\2\1\1\11"+
    "\1\1\1\0\2\1\1\0\2\1\1\11\1\1\1\0"+
    "\2\1\1\0\1\1\1\0\1\1\1\0\2\1\1\11"+
    "\1\1\1\11\1\1\1\0\2\1\1\0\2\1\1\0"+
    "\2\1\1\11\1\1\1\11\4\1\1\11\2\1\1\0"+
    "\1\1\1\0\3\1\2\11\1\1\1\11\1\1\1\0"+
    "\2\1\2\0\2\1\1\0\2\1\2\0\1\1\1\0"+
    "\2\1\1\11\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\11\1\1"+
    "\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[256];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Error Lexico: " + yytext() + " | Fila:" + yyline + " | Columna: " + yycolumn);
            }
          // fall through
          case 66: break;
          case 2:
            { /* Espacios en blanco se ignoran */
            }
          // fall through
          case 67: break;
          case 3:
            { yychar=1;
            }
          // fall through
          case 68: break;
          case 4:
            { return new Symbol(sym.NEGADO,yycolumn,yyline, yytext());
            }
          // fall through
          case 69: break;
          case 5:
            { return new Symbol(sym.DOLAR,yycolumn,yyline, yytext());
            }
          // fall through
          case 70: break;
          case 6:
            { return new Symbol(sym.PARI,yycolumn,yyline, yytext());
            }
          // fall through
          case 71: break;
          case 7:
            { return new Symbol(sym.PARD,yycolumn,yyline, yytext());
            }
          // fall through
          case 72: break;
          case 8:
            { return new Symbol(sym.POR,yycolumn,yyline, yytext());
            }
          // fall through
          case 73: break;
          case 9:
            { return new Symbol(sym.MAS,yycolumn,yyline, yytext());
            }
          // fall through
          case 74: break;
          case 10:
            { return new Symbol(sym.COMA,yycolumn,yyline, yytext());
            }
          // fall through
          case 75: break;
          case 11:
            { return new Symbol(sym.MENOS,yycolumn,yyline, yytext());
            }
          // fall through
          case 76: break;
          case 12:
            { return new Symbol(sym.PUNTO,yycolumn,yyline, yytext());
            }
          // fall through
          case 77: break;
          case 13:
            { return new Symbol(sym.DIVIDIDO,yycolumn,yyline, yytext());
            }
          // fall through
          case 78: break;
          case 14:
            { return new Symbol(sym.ENTERO, yycolumn, yyline, yytext());
            }
          // fall through
          case 79: break;
          case 15:
            { return new Symbol(sym.DOSPUNTOS,yycolumn,yyline, yytext());
            }
          // fall through
          case 80: break;
          case 16:
            { return new Symbol(sym.PUNTOYCOMA,yycolumn,yyline, yytext());
            }
          // fall through
          case 81: break;
          case 17:
            { return new Symbol(sym.MENOR,yycolumn,yyline, yytext());
            }
          // fall through
          case 82: break;
          case 18:
            { return new Symbol(sym.IGUAL,yycolumn,yyline, yytext());
            }
          // fall through
          case 83: break;
          case 19:
            { return new Symbol(sym.MAYOR,yycolumn,yyline, yytext());
            }
          // fall through
          case 84: break;
          case 20:
            { return new Symbol(sym.IDENTI,yycolumn,yyline, yytext());
            }
          // fall through
          case 85: break;
          case 21:
            { return new Symbol(sym.CORI,yycolumn,yyline, yytext());
            }
          // fall through
          case 86: break;
          case 22:
            { return new Symbol(sym.CORD,yycolumn,yyline, yytext());
            }
          // fall through
          case 87: break;
          case 23:
            { return new Symbol(sym.LLAVEI,yycolumn,yyline, yytext());
            }
          // fall through
          case 88: break;
          case 24:
            { return new Symbol(sym.LLAVED,yycolumn,yyline, yytext());
            }
          // fall through
          case 89: break;
          case 25:
            { return new Symbol(sym.DISTINTO,yycolumn,yyline, yytext());
            }
          // fall through
          case 90: break;
          case 26:
            { return new Symbol(sym.CADENA,yycolumn,yyline, yytext());
            }
          // fall through
          case 91: break;
          case 27:
            { return new Symbol(sym.RAND,yycolumn,yyline, yytext());
            }
          // fall through
          case 92: break;
          case 28:
            { return new Symbol(sym.CARACTER,yycolumn,yyline, yytext());
            }
          // fall through
          case 93: break;
          case 29:
            { return new Symbol(sym.INCREMENTO,yycolumn,yyline, yytext());
            }
          // fall through
          case 94: break;
          case 30:
            { return new Symbol(sym.DECREMENTO,yycolumn,yyline, yytext());
            }
          // fall through
          case 95: break;
          case 31:
            { return new Symbol(sym.MENORIGUAL,yycolumn,yyline, yytext());
            }
          // fall through
          case 96: break;
          case 32:
            { return new Symbol(sym.IGUALIGUAL,yycolumn,yyline, yytext());
            }
          // fall through
          case 97: break;
          case 33:
            { return new Symbol(sym.MAYORIGUAL,yycolumn,yyline, yytext());
            }
          // fall through
          case 98: break;
          case 34:
            { return new Symbol(sym.RDO,yycolumn,yyline, yytext());
            }
          // fall through
          case 99: break;
          case 35:
            { return new Symbol(sym.RIF,yycolumn,yyline, yytext());
            }
          // fall through
          case 100: break;
          case 36:
            { return new Symbol(sym.ROR,yycolumn,yyline, yytext());
            }
          // fall through
          case 101: break;
          case 37:
            { System.out.println(yytext());
            }
          // fall through
          case 102: break;
          case 38:
            { return new Symbol(sym.DECIMAL,yycolumn,yyline, yytext());
            }
          // fall through
          case 103: break;
          case 39:
            { return new Symbol(sym.RFOR,yycolumn,yyline, yytext());
            }
          // fall through
          case 104: break;
          case 40:
            { return new Symbol(sym.RINT,yycolumn,yyline, yytext());
            }
          // fall through
          case 105: break;
          case 41:
            { return new Symbol(sym.RBOOL,yycolumn,yyline, yytext());
            }
          // fall through
          case 106: break;
          case 42:
            { return new Symbol(sym.RCASE,yycolumn,yyline, yytext());
            }
          // fall through
          case 107: break;
          case 43:
            { return new Symbol(sym.RCHAR,yycolumn,yyline, yytext());
            }
          // fall through
          case 108: break;
          case 44:
            { return new Symbol(sym.REJEX,yycolumn,yyline, yytext());
            }
          // fall through
          case 109: break;
          case 45:
            { return new Symbol(sym.RELSE,yycolumn,yyline, yytext());
            }
          // fall through
          case 110: break;
          case 46:
            { return new Symbol(sym.RMAIN,yycolumn,yyline, yytext());
            }
          // fall through
          case 111: break;
          case 47:
            { return new Symbol(sym.RTRUE,yycolumn,yyline, yytext());
            }
          // fall through
          case 112: break;
          case 48:
            { return new Symbol(sym.RVOID,yycolumn,yyline, yytext());
            }
          // fall through
          case 113: break;
          case 49:
            { return new Symbol(sym.RBREAK,yycolumn,yyline, yytext());
            }
          // fall through
          case 114: break;
          case 50:
            { return new Symbol(sym.RFALSE,yycolumn,yyline, yytext());
            }
          // fall through
          case 115: break;
          case 51:
            { return new Symbol(sym.RWHILE,yycolumn,yyline, yytext());
            }
          // fall through
          case 116: break;
          case 52:
            { return new Symbol(sym.RWRITE,yycolumn,yyline, yytext());
            }
          // fall through
          case 117: break;
          case 53:
            { return new Symbol(sym.RDOUBLE,yycolumn,yyline, yytext());
            }
          // fall through
          case 118: break;
          case 54:
            { return new Symbol(sym.RSTRING,yycolumn,yyline, yytext());
            }
          // fall through
          case 119: break;
          case 55:
            { return new Symbol(sym.RSWITCH,yycolumn,yyline, yytext());
            }
          // fall through
          case 120: break;
          case 56:
            { return new Symbol(sym.RTITULO,yycolumn,yyline, yytext());
            }
          // fall through
          case 121: break;
          case 57:
            { return new Symbol(sym.RCONSOLE,yycolumn,yyline, yytext());
            }
          // fall through
          case 122: break;
          case 58:
            { return new Symbol(sym.RDEFAULT,yycolumn,yyline, yytext());
            }
          // fall through
          case 123: break;
          case 59:
            { return new Symbol(sym.RTITULOX,yycolumn,yyline, yytext());
            }
          // fall through
          case 124: break;
          case 60:
            { return new Symbol(sym.RTITULOY,yycolumn,yyline, yytext());
            }
          // fall through
          case 125: break;
          case 61:
            { return new Symbol(sym.RVALORES,yycolumn,yyline, yytext());
            }
          // fall through
          case 126: break;
          case 62:
            { return new Symbol(sym.RNEWVAL,yycolumn,yyline, yytext());
            }
          // fall through
          case 127: break;
          case 63:
            { return new Symbol(sym.RPIE,yycolumn,yyline, yytext());
            }
          // fall through
          case 128: break;
          case 64:
            { return new Symbol(sym.RBARRAS,yycolumn,yyline, yytext());
            }
          // fall through
          case 129: break;
          case 65:
            { return new Symbol(sym.RGLOBALES,yycolumn,yyline, yytext());
            }
          // fall through
          case 130: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
