
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package StatPy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 17;
  public static final int PUNTOYCOMA = 9;
  public static final int IGUAL = 10;
  public static final int DECIMAL = 21;
  public static final int IDENTI = 8;
  public static final int DIVIDIDO = 19;
  public static final int RSTRING = 15;
  public static final int RMAIN = 3;
  public static final int PARI = 4;
  public static final int LLAVEI = 6;
  public static final int PARD = 5;
  public static final int LLAVED = 7;
  public static final int RINT = 11;
  public static final int POR = 18;
  public static final int RBOOL = 14;
  public static final int RVOID = 2;
  public static final int EOF = 0;
  public static final int RDOUBLE = 12;
  public static final int error = 1;
  public static final int RCHAR = 13;
  public static final int ENTERO = 20;
  public static final int MAS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RVOID",
  "RMAIN",
  "PARI",
  "PARD",
  "LLAVEI",
  "LLAVED",
  "IDENTI",
  "PUNTOYCOMA",
  "IGUAL",
  "RINT",
  "RDOUBLE",
  "RCHAR",
  "RBOOL",
  "RSTRING",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "ENTERO",
  "DECIMAL"
  };
}

