
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package StatPy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 49;
  public static final int DISTINTO = 31;
  public static final int RSTRING = 15;
  public static final int RTRUE = 24;
  public static final int RWHILE = 40;
  public static final int POR = 18;
  public static final int PUNTOYCOMA = 9;
  public static final int ENTERO = 20;
  public static final int RVOID = 2;
  public static final int RDEFAULT = 48;
  public static final int IDENTI = 8;
  public static final int RFALSE = 25;
  public static final int RELSE = 39;
  public static final int RNEWVAL = 56;
  public static final int MENORIGUAL = 28;
  public static final int IGUAL = 10;
  public static final int CARACTER = 23;
  public static final int DIVIDIDO = 19;
  public static final int RDOUBLE = 12;
  public static final int INCREMENTO = 44;
  public static final int RCONSOLE = 35;
  public static final int RDO = 41;
  public static final int MAYORIGUAL = 29;
  public static final int EOF = 0;
  public static final int DECIMAL = 21;
  public static final int DECREMENTO = 43;
  public static final int error = 1;
  public static final int COMA = 57;
  public static final int RBARRAS = 51;
  public static final int CADENA = 22;
  public static final int MENOS = 17;
  public static final int MENOR = 26;
  public static final int RWRITE = 36;
  public static final int RCHAR = 13;
  public static final int MAYOR = 27;
  public static final int RCASE = 46;
  public static final int PUNTO = 37;
  public static final int IGUALIGUAL = 30;
  public static final int PARI = 4;
  public static final int CORI = 53;
  public static final int PARD = 5;
  public static final int RPIE = 52;
  public static final int RSWITCH = 45;
  public static final int ROR = 33;
  public static final int RINT = 11;
  public static final int LLAVEI = 6;
  public static final int CORD = 54;
  public static final int RGLOBALES = 50;
  public static final int RFOR = 42;
  public static final int RBOOL = 14;
  public static final int LLAVED = 7;
  public static final int RBREAK = 47;
  public static final int DOLAR = 55;
  public static final int RIF = 38;
  public static final int RAND = 32;
  public static final int NEGADO = 34;
  public static final int MAS = 16;
  public static final int RMAIN = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RVOID",
  "RMAIN",
  "PARI",
  "PARD",
  "LLAVEI",
  "LLAVED",
  "IDENTI",
  "PUNTOYCOMA",
  "IGUAL",
  "RINT",
  "RDOUBLE",
  "RCHAR",
  "RBOOL",
  "RSTRING",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "CARACTER",
  "RTRUE",
  "RFALSE",
  "MENOR",
  "MAYOR",
  "MENORIGUAL",
  "MAYORIGUAL",
  "IGUALIGUAL",
  "DISTINTO",
  "RAND",
  "ROR",
  "NEGADO",
  "RCONSOLE",
  "RWRITE",
  "PUNTO",
  "RIF",
  "RELSE",
  "RWHILE",
  "RDO",
  "RFOR",
  "DECREMENTO",
  "INCREMENTO",
  "RSWITCH",
  "RCASE",
  "RBREAK",
  "RDEFAULT",
  "DOSPUNTOS",
  "RGLOBALES",
  "RBARRAS",
  "RPIE",
  "CORI",
  "CORD",
  "DOLAR",
  "RNEWVAL",
  "COMA"
  };
}

